apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: log-generator-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-generator
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: berserker5000/log_generator:latest
        env:
          - name: NUM_THREADS
            value: "100"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
